extends:
  - standard
  - prettier
  - prettier/standard

parser: babel-eslint

plugins:
  - standard
  - prettier

globals:
  _: true
  $: true
  addClass: true
  createButton: true
  createEl: true
  createSpan: true
  el: true
  FileLoader: true
  global: true
  HotKeys: true
  kinka: true
  removeClass: true
  tabs: true
  Tabs: true
  TaskList: true
  taskList: true
  toggleClass: true
  WebLogger: true

env:
  browser: true

rules:
  # no-undef: 0
  prettier/prettier:
    - error
    - trailingComma: es5
      singleQuote: true
      semi: false

  # TODO: The following rules should be removed incrementally in order to fully
  # integrate lint rules from the Standard ESLint config and Prettier
