language: node_js
branches:
  only:
    - master
node_js:
  - "node"
cache:
  yarn: true
  directories:
      - "node_modules"
install:
  - yarn
script:
  - yarn lint-js
after_success:
  - if [ ${TRAVIS_BRANCH} = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ];then
    yarn build-prod;
    npm publish;
    fi
