language: node_js
branches:
  only:
    - master
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
install:
  - npm ci
script:
  - npm audit
  - npm run lint
  - npm run build
after_success:
  - if [ ${TRAVIS_BRANCH} = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ];then
    npm publish;
    fi
